/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orçamentoDeMarketing.UI;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import orçamentoDeMarketing.classes.model.video.Animacao;
import orçamentoDeMarketing.classes.model.video.Filmagem;
import orçamentoDeMarketing.listas.ListaVideos;

/**
 *
 * @author rodol
 */
public class VideoUI extends javax.swing.JFrame {

    /**
     * Creates new form Video
     */
    public VideoUI() {
        initComponents();
        spinnerQuantidade.setModel(new SpinnerNumberModel(0, 0, 1000000, 1));
    }

    ListaVideos listaVideos = new ListaVideos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonVoltarPagina = new javax.swing.JButton();
        txtVideo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtQuantidade = new javax.swing.JLabel();
        spinnerQuantidade = new javax.swing.JSpinner();
        txtTipo = new javax.swing.JLabel();
        radioButton1 = new javax.swing.JRadioButton();
        radioButton2 = new javax.swing.JRadioButton();
        buttonAjudaTipoVideo = new javax.swing.JButton();
        txtDuracao = new javax.swing.JLabel();
        formattedTxtFieldSegundos = new javax.swing.JFormattedTextField();
        txtSegundos = new javax.swing.JLabel();
        buttonAddVideo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(237, 126, 49));
        jPanel2.setForeground(new java.awt.Color(237, 126, 49));

        buttonVoltarPagina.setBackground(new java.awt.Color(237, 125, 49));
        buttonVoltarPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orçamentoDeMarketing/images/back-page-icon.png"))); // NOI18N
        buttonVoltarPagina.setBorder(null);
        buttonVoltarPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVoltarPaginaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonVoltarPaginaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonVoltarPaginaMouseExited(evt);
            }
        });
        buttonVoltarPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarPaginaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonVoltarPagina)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonVoltarPagina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtVideo.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        txtVideo.setForeground(new java.awt.Color(237, 125, 49));
        txtVideo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVideo.setText("VÍDEO");

        jPanel3.setBackground(new java.awt.Color(60, 60, 60));

        txtQuantidade.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuantidade.setText("Quantidade:");

        spinnerQuantidade.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        spinnerQuantidade.setMinimumSize(new java.awt.Dimension(64, 30));

        txtTipo.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipo.setText("Tipo:");

        radioButton1.setBackground(new java.awt.Color(60, 60, 60));
        buttonGroup.add(radioButton1);
        radioButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        radioButton1.setForeground(java.awt.Color.white);
        radioButton1.setText("Filmagem");

        radioButton2.setBackground(new java.awt.Color(60, 60, 60));
        buttonGroup.add(radioButton2);
        radioButton2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        radioButton2.setForeground(java.awt.Color.white);
        radioButton2.setText("Animação");
        radioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton2ActionPerformed(evt);
            }
        });

        buttonAjudaTipoVideo.setBackground(new java.awt.Color(237, 125, 49));
        buttonAjudaTipoVideo.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        buttonAjudaTipoVideo.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjudaTipoVideo.setText("?");
        buttonAjudaTipoVideo.setBorder(null);
        buttonAjudaTipoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaTipoVideoActionPerformed(evt);
            }
        });

        txtDuracao.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        txtDuracao.setForeground(new java.awt.Color(255, 255, 255));
        txtDuracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDuracao.setText("Duração: ");

        formattedTxtFieldSegundos.setBackground(new java.awt.Color(102, 102, 102));
        formattedTxtFieldSegundos.setForeground(new java.awt.Color(255, 255, 255));
        formattedTxtFieldSegundos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        formattedTxtFieldSegundos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        formattedTxtFieldSegundos.setName(""); // NOI18N
        formattedTxtFieldSegundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formattedTxtFieldSegundosMouseEntered(evt);
            }
        });
        formattedTxtFieldSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTxtFieldSegundosActionPerformed(evt);
            }
        });

        txtSegundos.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundos.setText("segundos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTxtFieldSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSegundos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTipo)
                        .addGap(29, 29, 29)
                        .addComponent(radioButton1)
                        .addGap(27, 27, 27)
                        .addComponent(radioButton2)
                        .addGap(33, 33, 33)
                        .addComponent(buttonAjudaTipoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade)
                    .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo)
                    .addComponent(radioButton1)
                    .addComponent(radioButton2)
                    .addComponent(buttonAjudaTipoVideo))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracao)
                    .addComponent(txtSegundos)
                    .addComponent(formattedTxtFieldSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        buttonAddVideo.setBackground(new java.awt.Color(237, 125, 49));
        buttonAddVideo.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonAddVideo.setForeground(new java.awt.Color(255, 255, 255));
        buttonAddVideo.setText("ADICIONAR");
        buttonAddVideo.setBorderPainted(false);
        buttonAddVideo.setFocusPainted(false);
        buttonAddVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtVideo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAddVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonAddVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarPaginaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVoltarPaginaMouseClicked

    private void buttonVoltarPaginaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarPaginaMouseEntered
        buttonVoltarPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orçamentoDeMarketing/images/back-page-icon-entered.png")));
    }//GEN-LAST:event_buttonVoltarPaginaMouseEntered

    private void buttonVoltarPaginaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarPaginaMouseExited
        buttonVoltarPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orçamentoDeMarketing/images/back-page-icon.png")));
    }//GEN-LAST:event_buttonVoltarPaginaMouseExited

    private void buttonVoltarPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarPaginaActionPerformed
        OpcoesUI op = new OpcoesUI();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarPaginaActionPerformed

    private void formattedTxtFieldSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTxtFieldSegundosActionPerformed

    }//GEN-LAST:event_formattedTxtFieldSegundosActionPerformed

    private void formattedTxtFieldSegundosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formattedTxtFieldSegundosMouseEntered
        formattedTxtFieldSegundos.setToolTipText("Apenas valores positivos e menores que 99.");
    }//GEN-LAST:event_formattedTxtFieldSegundosMouseEntered

    private void buttonAddVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddVideoActionPerformed
        radioButton1.setActionCommand("1");
        radioButton2.setActionCommand("2");
        double segundos = Double.parseDouble(formattedTxtFieldSegundos.getText());
        try {
            if(segundos < 0 || segundos > 90){
                throw new NumberFormatException();
            }
            if (buttonGroup.getSelection() == null || formattedTxtFieldSegundos.getValue() == null) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            } else {
                for (int i = 0; i < Integer.parseInt(spinnerQuantidade.getValue().toString()); i++) {
                    if (radioButton1.isSelected()) {
                        listaVideos.adicionar(new Filmagem(segundos,"filmagem"));
                    } else {
                        listaVideos.adicionar(new Animacao(segundos,"animação"));
                    }
                }
                JOptionPane.showMessageDialog(null, "Vídeo(s) adicionada com sucesso ao carrinho! ");
                OpcoesUI op = new OpcoesUI();
                op.setVisible(true);
                this.dispose();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Apenas números positivos e menores que 90 são aceitos no campo 'Duração'");
        }finally{
            formattedTxtFieldSegundos.setText("");
        }
    }//GEN-LAST:event_buttonAddVideoActionPerformed

    private void buttonAjudaTipoVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjudaTipoVideoActionPerformed
        JOptionPane.showMessageDialog(null, "Filmagem: \nUma gravação já pronta, iremos apenas editá-la.\n\n"
                + "Animação: \nCriação do zero. Maior valor agregado.");
    }//GEN-LAST:event_buttonAjudaTipoVideoActionPerformed

    private void radioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Video(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddVideo;
    private javax.swing.JButton buttonAjudaTipoVideo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonVoltarPagina;
    private javax.swing.JFormattedTextField formattedTxtFieldSegundos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JSpinner spinnerQuantidade;
    private javax.swing.JLabel txtDuracao;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtSegundos;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtVideo;
    // End of variables declaration//GEN-END:variables
}
